name: pr-labeler
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and add label
        uses: actions/github-script@v7
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          script: |
            const payload = github.context.payload;
            if (payload && payload.pull_request) {
              const title = payload.pull_request.title;
              const prNumber = payload.pull_request.number;
              // Check if the title contains "APA" (case-insensitive)
              if (title.toLowerCase().includes('apa')) {
                // Add the "prior-auth" label to the PR
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: ['prior-auth']
                });
              } 
            } else {
              console.error('Payload or pull_request not found in the context.');
            }



# # The bot always updates the labels, add/remove as necessary [default: false]
# alwaysReplace: false
# # Treats the text and labels as case sensitive [default: true]
# caseSensitive: true
# # Array of labels to be applied to the PR [default: []]
# customLabels:
#   # Finds the `text` within the PR title and body and applies the `label`
#   - text: '#APA'
#     label: 'bug'
# # Search the title of the PR for the `text` [default: true]
# searchTitle: true
# # Search for whole words only [default: false]
# wholeWords: false
# # Update
