name: pr-labeler
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."







# # .github/pr-labeler.yml
# # The bot always updates the labels, add/remove as necessary [default: false]
# alwaysReplace: false
# # Treats the text and labels as case sensitive [default: true]
# caseSensitive: true
# # Array of labels to be applied to the PR [default: []]
# customLabels:
#   # Finds the `text` within the PR title and body and applies the `label`
#   - text: '#APA'
#     label: 'bug'
# # Search the title of the PR for the `text` [default: true]
# searchTitle: true
# # Search for whole words only [default: false]
# wholeWords: false
# # Update
