name: pr-labeler
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and add label
        uses: actions/github-script@v7
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          script: |
            
            if (!github) {
              console.error('github not found.');
              process.exit(1); // Exit with an error code
            }
            if (!github.context){
              console.error('context not found in the context.');
              process.exit(1); // Exit with an error code
            }
            const payload = github.context.payload;
            if (payload && payload.pull_request) {
              const title = payload.pull_request.title;
              const prNumber = payload.pull_request.number;
              // Check if the title contains "APA" (case-insensitive)
              if (title.toLowerCase().includes('apa')) {
                // Add the "prior-auth" label to the PR
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: ['prior-auth']
                });
              } 
            } else {
              console.error('Payload or pull_request not found in the context.');
            }

